#MotorVCS setting file
#Wed Apr 03 14:47:34 CST 2024

#通道设置
ch=channels
ch.ch1=CMD
ch.ch2=MODE
ch.ch3=SYS_VOL
ch.ch4=SYS_CUR
ch.ch5=Torque_VOL
ch.ch6=CHG_CUR
ch.ch7=MOT_VOL
ch.ch8=MOT_CUR
ch.ch9=MOT_SPEED
ch.ch10=Angle_Motor
ch.ch11=TEMP
ch.ch12=SETSPEED
ch.ch13=Angle_End-Effector
ch.ch14=status



#连接设置 192.168.1.1:8899
conn.ip=192.168.1.1
conn.port=8899



#串口设置
com.baudrate=460800
com.databits=8
#可接受参数1~3  (ONE_STOP_BIT, ONE_POINT_FIVE_STOP_BITS, TWO_STOP_BITS)
com.stopbits=1
#可接受参数0~4  (NO_PARITY, EVEN_PARITY, ODD_PARITY, MARK_PARITY, SPACE_PARITY)
com.parity=0



#调试输入提示符 输出提示符
msg.input=>>\ 
msg.output=<<\ 



#Douglas–Peucker压缩算法参数
#压缩单元，默认每500个点(5秒)压缩计算显示一次
chart.unit=100
#压缩距离阈值参数，默认0.5达到较好状态，参数含义见https://blog.csdn.net/deram_boy/article/details/39177015
#参数0.5在曲线1与曲线7约可保留60%点，参数值为0.1约保留70%点 近似极限。  在其余曲线上约可压缩掉98%以上点位。
chart.distance=0.5



#记录设置
record.unit=3000